server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/proselyte_webflux_security
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/proselyte_webflux_security
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

jwt:
  password:
    encoder:
      secret: f
      iteration: 64
      keylength: 256
  secret: secret
  expiration: 3600
  issuer: proselyte